name: Build Mac app (arm64)

on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: macos-14          # Apple-silicon runner

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    - name: Install build deps
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        brew install tcl-tk || true      # Tk libs for _tkinter

    - name: Freeze with PyInstaller (arm64)
      run: |
        pyinstaller googlemaps_scraper.py \
                   --windowed \
                   --name "GMapsClaimChecker"

    - name: Ad-hoc code-sign (prevents “damaged” error)
      run: |
        codesign --force --deep --sign - dist/GMapsClaimChecker.app

    - name: Zip the .app
      run: |
        cd dist
        ditto -c -k --sequesterRsrc --keepParent \
              GMapsClaimChecker.app GMapsClaimChecker-arm64.zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: GMapsClaimChecker-arm64
        path: dist/GMapsClaimChecker-arm64.zip
