name: Build Mac app (arm64)

on:
  workflow_dispatch:          # manual trigger
  push:
    tags: [ 'v*' ]            # build whenever you push a tag like v1.0

jobs:
  build:
    runs-on: macos-14         # Apple-silicon GitHub runner (arm64)

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build deps
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        # Tk headers are occasionally missing on the runner:
        brew install tcl-tk || true

    - name: Freeze with PyInstaller (arm64)
      run: |
        pyinstaller googlemaps_scraper.py \
                   --windowed \
                   --name "GMapsClaimChecker"

    - name: Zip the .app
      run: |
        cd dist
        ditto -c -k --sequesterRsrc --keepParent \
              GMapsClaimChecker.app GMapsClaimChecker-arm64.zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: GMapsClaimChecker-arm64
        path: dist/GMapsClaimChecker-arm64.zip
